baseURL = "https://vsantona.me/"
canonifyURLs = false
relativeURLs = true
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Vincenzo Santonastaso"
theme = "PaperMod"

[[menu.main]]
name = "About"
url = "/about/"
weight = 10

[[menu.main]]
name = "Posts"
url = "/posts/"
weight = 20

[[menu.main]]
name = "Resume"
url = "/resume/"
weight = 3

[params]
author = "Vincenzo Santonastaso"
description = "Software Developer | Backend, Cloud, Architetture Moderne"
showMenu = true

[[params.socialIcons]]
name = "github"
url = "https://github.com/vsantona"

[[params.socialIcons]]
name = "linkedin"
url = "https://www.linkedin.com/in/vincenzo-santonastaso-549945b1/"


[[params.socialIcons]]
name = "gmail"
url = "mailto:vincenzo.santonastaso.it@gmail.com"